name: CI/CD Site HTML

on: 
  push:
    branches: ["main"]

jobs:
  validate:
    runs-on: ubunto-latest
    steps:
      - uses: actions/checkout@v3
      - name: Validar HTML
        uses: Cyb3r-Jak3/html5validator-action@v0.4.4

  deploy:
    runs-on: ubuntu-latest
    needs: validate # só roda se a validação passar
    steps:
        - uses: actions/checkout@v3
        - name: Deploy no GitHub Pages
          uses: peaceiris/actions-gh-pages@v3
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: ./
